// <auto-generated />
using System;
using CarBookingApplicationProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBookingApplicationProject.Migrations
{
    [DbContext(typeof(CarBookingApplicationProjectContext))]
    [Migration("20250208051535_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeedbackDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Great ride! The driver was very professional.",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3034),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3035),
                            FeedbackDateTime = new DateTime(2025, 2, 6, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3020),
                            Rating = 5,
                            RideId = 1,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comments = "The ride was okay, but the car was a bit dirty.",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3038),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3038),
                            FeedbackDateTime = new DateTime(2025, 2, 7, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3037),
                            Rating = 3,
                            RideId = 2,
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Marina Bay Sands, 10 Bayfront Ave",
                            City = "Singapore",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3167),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3168),
                            Latitude = 1.290270m,
                            Longitude = 103.851959m,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sentosa Island",
                            City = "Singapore",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3170),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3171),
                            Latitude = 1.352083m,
                            Longitude = 103.819836m,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 25.50m,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3223),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3223),
                            PaymentStatus = "Completed",
                            PaymentType = "Credit Card",
                            RideId = 1,
                            TransactionDateTime = new DateTime(2025, 2, 8, 12, 45, 35, 202, DateTimeKind.Local).AddTicks(3221),
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 30.00m,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3226),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3226),
                            PaymentStatus = "Pending",
                            PaymentType = "Cash",
                            RideId = 2,
                            TransactionDateTime = new DateTime(2025, 2, 8, 13, 5, 35, 202, DateTimeKind.Local).AddTicks(3225),
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3273),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3273),
                            DiscountAmount = 10.00m,
                            EndDate = new DateTime(2025, 2, 28, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3272),
                            PromotionCode = "SAVE10",
                            StartDate = new DateTime(2025, 1, 29, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3271),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3276),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3276),
                            DiscountAmount = 20.00m,
                            EndDate = new DateTime(2025, 2, 23, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3275),
                            PromotionCode = "WELCOME20",
                            StartDate = new DateTime(2025, 2, 3, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3275),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DropoffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<decimal>("RideCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RideStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ride");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3325),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3326),
                            DropoffTime = new DateTime(2025, 2, 8, 12, 15, 35, 202, DateTimeKind.Local).AddTicks(3323),
                            LocationId = 1,
                            PickupTime = new DateTime(2025, 2, 8, 11, 15, 35, 202, DateTimeKind.Local).AddTicks(3323),
                            PromotionId = 1,
                            RideCost = 25.50m,
                            RideStatus = "Completed",
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3328),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3329),
                            DropoffTime = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3327),
                            LocationId = 2,
                            PickupTime = new DateTime(2025, 2, 8, 12, 15, 35, 202, DateTimeKind.Local).AddTicks(3327),
                            PromotionId = 2,
                            RideCost = 30.00m,
                            RideStatus = "Ongoing",
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequentLocations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassenger")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredPickupTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptanceRate = "",
                            Address = "Jurong East",
                            CarLicense = "",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3379),
                            DateOfBirth = "05/03/2001",
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3379),
                            DisplayName = "Jordan",
                            DrivingExperience = "",
                            Email = "Jordan01239@gmail.com",
                            FrequentLocations = "Jurong East, Clementi",
                            Gender = "Male",
                            IsDriver = false,
                            IsPassenger = true,
                            PhoneNumber = "97593043",
                            PreferredPickupTime = "Morning",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AcceptanceRate = "75.5%",
                            Address = "Jurong West",
                            CarLicense = "SGX1234A",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3382),
                            DateOfBirth = "22/10/2000",
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3383),
                            DisplayName = "Jeff",
                            DrivingExperience = "2 years",
                            Email = "Jeff019231@gmail.com",
                            FrequentLocations = "Jurong West, Pioneer",
                            Gender = "Male",
                            IsDriver = true,
                            IsPassenger = false,
                            PhoneNumber = "93843943",
                            PreferredPickupTime = "Morning",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingApplicationProject.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3427),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3428),
                            LicensePlate = "MBX3829B",
                            Manufacturer = "Toyota",
                            MaximumPassengers = 4,
                            Model = "Corolla",
                            Status = "Active",
                            UpdatedBy = "System",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3430),
                            DateUpdated = new DateTime(2025, 2, 8, 13, 15, 35, 202, DateTimeKind.Local).AddTicks(3430),
                            LicensePlate = "JKX8273C",
                            Manufacturer = "Honda",
                            MaximumPassengers = 4,
                            Model = "Civic",
                            Status = "Active",
                            UpdatedBy = "System",
                            UserId = 2,
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
